export const iconCategories = {
    "Food & Dining": [
        "UtensilsCrossed",
        "Coffee",
        "Pizza",
        "Sandwich",
        "IceCream",
        "Cake",
        "Apple",
        "Banana",
        "Cherry",
        "Grape",
        "Wine",
        "Beer",
        "ChefHat",
        "CookingPot",
        "Soup",
    ],
    Transportation: [
        "Car",
        "Bus",
        "Train",
        "Plane",
        "Bike",
        "Motorcycle",
        "Truck",
        "Taxi",
        "Ship",
        "Rocket",
        "CarFront",
        "Fuel",
        "ParkingCircle",
        "Navigation",
        "MapPin",
    ],
    Entertainment: [
        "Film",
        "Music",
        "Gamepad2",
        "Tv",
        "Radio",
        "Camera",
        "Video",
        "Headphones",
        "Mic",
        "Guitar",
        "Piano",
        "Drum",
        "Theater",
        "Ticket",
        "PartyPopper",
    ],
    Shopping: [
        "ShoppingBag",
        "ShoppingCart",
        "Store",
        "Gift",
        "Package",
        "Shirt",
        "Glasses",
        "Watch",
        "Gem",
        "Crown",
        "Handbag",
        "Footprints",
        "Scissors",
        "Palette",
        "Brush",
    ],
    Healthcare: [
        "Heart",
        "Stethoscope",
        "Pill",
        "Syringe",
        "Thermometer",
        "Bandage",
        "Cross",
        "Activity",
        "Brain",
        "Eye",
        "Ear",
        "Tooth",
        "Baby",
        "Wheelchair",
        "FirstAid",
    ],
    Utilities: [
        "Zap",
        "Lightbulb",
        "Flame",
        "Droplets",
        "Wifi",
        "Phone",
        "Smartphone",
        "Laptop",
        "Monitor",
        "Router",
        "Battery",
        "Plug",
        "Cable",
        "Signal",
        "Antenna",
    ],
    "Business & Work": [
        "Briefcase",
        "Building",
        "Building2",
        "Factory",
        "Warehouse",
        "Store",
        "Bank",
        "Landmark",
        "Calculator",
        "PieChart",
        "BarChart",
        "TrendingUp",
        "DollarSign",
        "CreditCard",
        "Coins",
    ],
    Education: [
        "GraduationCap",
        "BookOpen",
        "Book",
        "Library",
        "School",
        "Pencil",
        "Pen",
        "Ruler",
        "Calculator",
        "Globe",
        "Microscope",
        "FlaskConical",
        "Atom",
        "Trophy",
        "Award",
    ],
    "Home & Garden": [
        "Home",
        "Bed",
        "Sofa",
        "Lamp",
        "Key",
        "Lock",
        "Door",
        "Window",
        "Hammer",
        "Wrench",
        "Screwdriver",
        "Paintbrush",
        "Flower",
        "TreePine",
        "Leaf",
        "Sprout",
    ],
    "Sports & Fitness": [
        "Dumbbell",
        "Activity",
        "Target",
        "Trophy",
        "Medal",
        "Football",
        "Basketball",
        "Tennis",
        "Golf",
        "Bike",
        "Swimming",
        "Running",
        "Hiking",
        "Mountain",
        "Compass",
    ],
    Travel: [
        "Plane",
        "MapPin",
        "Map",
        "Compass",
        "Camera",
        "Backpack",
        "Luggage",
        "Passport",
        "Globe",
        "Mountain",
        "Palmtree",
        "Sun",
        "Umbrella",
        "Tent",
        "Caravan",
    ],
    Technology: [
        "Laptop",
        "Smartphone",
        "Monitor",
        "Keyboard",
        "Mouse",
        "Headphones",
        "Speaker",
        "Microchip",
        "HardDrive",
        "Usb",
        "Wifi",
        "Bluetooth",
        "Battery",
        "Plug",
        "Cable",
    ],
    Finance: [
        "DollarSign",
        "CreditCard",
        "Banknote",
        "Coins",
        "PiggyBank",
        "Wallet",
        "Receipt",
        "Calculator",
        "TrendingUp",
        "TrendingDown",
        "BarChart",
        "PieChart",
        "Target",
        "Percent",
        "Euro",
    ],
}

export const IconColorOptions = [
    { value: "#FF6B6B", label: "Red", color: "#FF6B6B" },
    { value: "#4ECDC4", label: "Teal", color: "#4ECDC4" },
    { value: "#45B7D1", label: "Blue", color: "#45B7D1" },
    { value: "#96CEB4", label: "Green", color: "#96CEB4" },
    { value: "#FFEAA7", label: "Yellow", color: "#FFEAA7" },
    { value: "#DDA0DD", label: "Purple", color: "#DDA0DD" },
    { value: "#FFB6C1", label: "Pink", color: "#FFB6C1" },
    { value: "#98D8C8", label: "Mint", color: "#98D8C8" },
    { value: "#F39C12", label: "Orange", color: "#F39C12" },
    { value: "#E74C3C", label: "Crimson", color: "#E74C3C" },
    { value: "#3498DB", label: "Sky Blue", color: "#3498DB" },
    { value: "#2ECC71", label: "Emerald", color: "#2ECC71" },
    { value: "#9B59B6", label: "Violet", color: "#9B59B6" },
    { value: "#34495E", label: "Dark Gray", color: "#34495E" },
    { value: "#16A085", label: "Turquoise", color: "#16A085" },
    { value: "#E67E22", label: "Carrot", color: "#E67E22" },
]